config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
  
         has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet creado exitosamente.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/be94cb8174.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>

    <script type="text/javascript">
      document.querySelectorAll('.notification').forEach(notification => {
        setTimeout(() => {
          notification.style.display = 'none'
        }, 2000);
      });
    </script>


    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">TwitterClone</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
                <% if user_signed_in? %>
                  <p class="control">
                    <%= link_to "Nuevo Tweet", new_tweet_path, class: "button is-info is-inverted"%>
                  </p>
                  <p class="control">
                    <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                  </p>
                  <p class="control">
                    <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "button is-info" %>
                  </p>
                <% else %>
                  <p class="control">
                    <%= link_to "Iniciar sesión", new_user_session_path, class: "button is-info"%>
                  </p>
                  <p class="control">
                    <%= link_to "Regístrate", new_user_registration_path, class: "button is-info" %>                
                  </p>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>




    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
        <article class="media box">
            <figure class="media-left">
                <p class="image is64x64">
                    <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
                </p>
            </figure>
            <div class="media-content">
                <%= render 'tweets/form' %>
            </div>
        </article>
    <% end %>

    <% @tweets.each do |tweet| %>
        <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong><%=tweet.user.name%></strong><br/>
                    <small>@<%=tweet.user.username%></small><br/>
                    <p> <%= tweet.content%> </p>
                </div>
                <% if user_signed_in? %>
                    <nav class="level">
                        <div class="level-left is-mobile">
                            <%= link_to tweet, class: "level-item" do %>
                                <span class="icon"> <i class="fas fa-link" aria-hidden="true"></i> </span>
                            <% end %>
                            <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                                <span class="icon"> <i class="fas fa-edit" aria-hidden="true"></i> </span>
                            <% end %>
                            <%= link_to tweet, method: :delete, data: {confirm: "¿Borrar este Tweet?"} do %>
                                <span class="icon"> <i class="fas fa-trash" aria-hidden="true"></i> </span>
                            <% end %>
                        </div>
                    </nav>
                <% end %>
            </div>
        </article>
        </div>
    <% end %>
</div>

app/views/tweets/_form.html.erb
<% if false %>
  <%= form_with(model: tweet, local: true) do |form| %>
    <% if tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

<%= simple_form_for(@tweet) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :content, label: "Twitea algo!", input_html: {class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Escribe aquí tu tweet..." %>
    </div>
  </div>
  <%= f.button :submit, "Crear Tweet", class: "button is-info" %>
<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Perfíl</p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong><%= current_user.name %></strong><br/>
                            <small>@<%= current_user.username %></small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <div class="level is-mobile">
                <div class="level-item has-centered-text">
                    <div>
                    <p class="heading">Tweets</p>
                    <p class="title is-6"><%= current_user.tweets.count %></p>
                    </div>
                </div>
                <div class="level-item has-centered-text">
                    <div>
                    <p class="heading">Following</p>
                    <p class="title is-6">368</p>
                    </div>
                </div>
                <div class="level-item has-centered-text">
                    <div>
                    <p class="heading">Followers</p>
                    <p class="title is-6">501k</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Trends</p>
        <a href="" class="panel-block">Trend 1</a>
        <a href="" class="panel-block">Trend 2</a>
        <a href="" class="panel-block">Trend 3</a>
        <a href="" class="panel-block">Trend 4</a>
        <a href="" class="panel-block">Trend 5</a>
        <a href="" class="panel-block">Trend 6</a>
    </nav>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Cuentas para seguir</p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://avatarfiles.alphacoders.com/777/77704.jpg" alt="Avatar">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
						    <strong>David Bowie</strong><br/>
						    <small>@davidbowie</small><br/>
					    </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://pbs.twimg.com/profile_images/3307873424/15b1f6b6006ac3c86e39bbb02766c3df.jpeg" alt="Avatar">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>Bruce Springsteen</strong><br/>
                            <small>@springsteen</small><br/>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://pm1.narvii.com/6457/100ac33243d7b7fda397640362a77a41143402ae_128.jpg" alt="Avatar">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>Joan Jett</strong><br/>
                            <small>@joanjett</small><br/>
                        </p>
                    </div>
                </div>
            </article>
        </div>
    </nav>
</div>

app/views/tweets/edit.html.erb
<h1>Editando Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Mostrar', @tweet %> |
<%= link_to 'Volver Atrás', tweets_path %>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in?%>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-follow'%>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>Nuevo Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Volver Atrás', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Editar', edit_tweet_path(@tweet) %> |
<%= link_to 'Volver atrás', tweets_path %>